image: openbsd/latest
packages:
  - png
  - kcgi
sources:
  - https://git.sr.ht/~tleguern/libravatar.cgi
tasks:
  - build: |
      cd libravatar.cgi
      ./configure
      make
triggers:
  - action: email
    condition: failure
    to: "<tleguern+libravatar@bouledef.eu>"
